### ISSUE TITLE
if ACF is null the request errors out

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-api#71]
Came across a weird issue today on See Me, where this specific URL causes a 500 error:
`https://see-me-api.flywheelsites.com/wp-json/fuxt/v1/post?uri=%2Fartists%2Fcameron-michael-debe%2F&fields=acf&fields=children&fields=terms`

All other artists work fine. 

The is wp-debug message:

<img width="770" alt="api-err" src="https://github.com/user-attachments/assets/6dd206d1-4ce5-407e-8782-3dfbaf1a63e5">

It looks like an ACF error, so i thought maybe there was an empty field or something content related, but that's not the case.

Now i think it's an ACF issue with a child page, because if i remove the `children` term, it works.
I resaved all child pages, cleared cache, and enabled dev mode but still having the issue.

Can you take a look?

**Comment by rsm0128** [comment]
@dChiamp This [PR](https://github.com/funkhaus/fuxt-api/pull/72) should fix the issue. Please let me know if it doesn't work. Thanks!

**Comment by dChiamp** [comment]
@rsm0128 interestingly it looks like that worked for 2 of 3 of the pages with issues, but this one is still having issues:
`https://see-me-api.flywheelsites.com/wp-json/fuxt/v1/post?uri=/artists/cameron-michael-debe/new-museum-discover-demo/&fields=acf`

I drafted that page for now so i can make and deploy updates. 
Do you have access to this site?

**Comment by rsm0128** [comment]
@dChiamp There was another edge case for validation and I fixed it. Please check and let me know if you face any other issues.

**Comment by dChiamp** [comment]
OK looks like that fixed it! thanks @rsm0128
